### ISSUE TITLE
CLIK Algorithm not working

### ISSUE THREAD

**Issue by bademeister99** [RO-Projects/scara#16]
The Algorithm of the CLIK is not working properly.

**Comment by Elektron97** [comment]
Maybe your error in the CLIK algorithm implementation is the discrete integration. In particular, in your [node](https://github.com/RO-Projects/scara/blob/main/scara_robot/src/scara_control.cpp), if you use the ode1 method, the mathematical approximation of the derivative of the joint vector $\dot{q}$ is:

$$
\dot{q} \approx \frac{q_{k+1} - q_{k}}{T_s} \qquad q_{k+1} = q_k + T_s \ \dot{q}
$$

In your function, in this [line](https://github.com/RO-Projects/scara/blob/45570d844ee47be0de2ebd40f45e77c76968e434/scara_robot/src/scara_control.cpp#L208), you have to add the previous value of $q$, in order to compute correctly the integration.

**Comment by bademeister99** [comment]
I changed the integrator method and adjusted the K Matrix, die Robot is movin towards the desired position, but the algorithm is not able to set the error value close to zero. It seems like there is an offset

**Comment by bademeister99** [comment]
The published and actually reached joint angles are identical, so the problem must be in the Jacobian Matrix
`    jacob <<    -l1*sin(_theta1)-l2*sin(_theta1+_theta2), -l2*sin(_theta1+_theta2), 0,
                       l1*cos(_theta1) + l2*cos(_theta1+_theta2), l2*cos(_theta1+_theta2), 0,
                       0, 0, 1;`

**Comment by bademeister99** [comment]
![grafik](https://user-images.githubusercontent.com/123369589/218099575-577293fe-c857-48b0-ac38-efdee02bcfcb.png)
just the error for the x-direction remains. It indicates an error in the jacobian?

**Comment by bademeister99** [comment]
I forgot to use the actual joint values of the, robot. To compute the jacobian, now the two actual joint angles from **sensor_msgs/JointStates** are used
![grafik](https://user-images.githubusercontent.com/123369589/218135598-9845030e-52fe-413e-9e80-66f3d3054e85.png)
X and Y errors are converging really slow, in Z direction the converging happens faster

**Comment by bademeister99** [comment]
Issue resolved by using the joint angles **q** from the previous step to calculate the actual jacobian. Previously the measured angles have been used.

For validation see the Readme.
